### PR TITLE
Spike - Explore video integration using Panopto

### PR DESCRIPTION
**Pull request by ZHONGYU1111**
# Description

This document provides a detailed exploration of integrating Panopto's video functionalities into the OnTrack platform. Panopto, known for its robust video management features, offers potential enhancements in user engagement on OnTrack, especially in task submissions and discussions. The document covers various aspects, including video management, sharing, accessibility, and API integration. It outlines specific use cases, an integration approach focusing on secure authentication and embedding techniques, and highlights key security considerations. The final sections list essential development items and conclude with the anticipated benefits of this integration, positioning it as a crucial step toward enriching OnTrack's multimedia support.

### CODE REVIEW

**Comment by JayaniVimukthika** [comment]
Hi ZHONGYU,
This provides a detailed description of integrating Panopto's video functionalities into the OnTrack platform and addressed the necessary spike sections, requirement of embedding video content in task submissions, comments, and content.
Everything looks good. you can continue with your work.

**Comment by JayaniVimukthika** [comment]
According to the correct identification of integrating Panopto's video functionalities into the OnTrack platform, this section II provides a a clear guidance of Panopto integration with Ontrack. 
This describes all the steps starting from environment setup  with file locations to fetching videos including authentication services, component implementation, upload, and adding new services to Angular module.
This has addressed necessary spike sections and steps, everything looks perfect!

**Review by aNebula — APPROVED** [review]
LGTM

**Review by aNebula — APPROVED** [review]

**Review by aNebula — APPROVED** [review]

**Comment by aNebula** [comment]
@maddernd could you please merge this? I don't seem to have write access to this repo.

**Pull request merged**
