### PR TITLE
Create thoth-tech-worklog-guideline.md

### PR DESCRIPTION
**Pull request by ivanhub7**
# Description

_Please include a summary of the change and which issue is fixed. Please also include relevant
motivation and context. List any dependencies that are required for this change._

Fixes # (issue)

## Type of change

_Please delete options that are not relevant._

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as
      expected)
- [✓ ] Documentation (update or new)

## How Has This Been Tested?

_Please describe the tests that you ran to verify your changes. Provide instructions so we can
reproduce. Please also list any relevant details for your test configuration_

## Testing Checklist

- [ ] Tested in latest Chrome
- [ ] Tested in latest Safari
- [ ] Tested in latest Firefox

## Checklist

- [✓ ] My code follows the style guidelines of this project
- [✓ ] I have performed a self-review of my own code
- [ ] I have commented my code in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have requested a review from ... on the Pull Request

### CODE REVIEW

**Comment by Kachi-Okorie** [comment]
All checks passed. Good to go

**Comment by Kachi-Okorie** [comment]
Your last commit has lint error on how-to-publish-an-astro-website-to-netlify-guide.md file

**Comment by Kachi-Okorie** [comment]
Changes looks good. Please follow up with Amin to approve

**Comment by Kachi-Okorie** [comment]
@ivanhub7 as mentioned during the Standup. Create a netlify account and host the Documentation website on there to be able to generate the appropriate steps for the document.

**Comment by Kachi-Okorie** [comment]
[Create a Worklog to be adopted by the Company](https://trello.com/c/mlV5oD1a/90-create-a-worklog-to-be-adopted-by-the-company)

**Comment by ivanhub7** [comment]
[Create markdown files to showcase Splashkit's projects for the Documentation Website](https://trello.com/c/YAR7H07N/130-create-markdown-files-to-showcase-splashkits-projects-for-the-documentation-website)

**Comment by ivanhub7** [comment]
[Migrate Splashkit's Tutorial folder and files to the Documentation Website.](https://trello.com/c/SXNWj7GC/132-migrate-splashkits-tutorial-folder-and-files-to-the-documentation-website)

**Comment by ivanhub7** [comment]
[Review the folders in SplashKit determine which folder they fall under (Projects, Documentation, Issues and Resolution)](https://trello.com/c/RqpkKWgg/104-review-the-folders-in-splashkit-determine-which-folder-they-fall-under-projects-documentation-issues-and-resolution)

**Comment by Kachi-Okorie** [comment]
Always read the details of your failed checks

**Comment by ivanhub7** [comment]
[Migrate documents from Company Operations Repo to the Documentation Website.](https://trello.com/c/WQcrha3O/91-migrate-documents-from-company-operations-repo-to-the-documentation-website)

**Pull request closed without merging**
