### PR TITLE
Enhance/migrate view all units component

### PR DESCRIPTION
**Pull request by BrianJCal99**
# Description

Component review document and the progress on the task so far.

### CODE REVIEW

**Comment by BrianJCal99** [comment]
@AusBruce will review this PR.

**Comment by AusBruce** [comment]
Brian and I worked on this assignment for a while, putting in a lot of effort and time to study and conduct research. We have a few meetings to talk about the progress we have made so far. In my opinion, Brian is a highly cooperative team member who provides me with a wealth of tech expertise and insightful references.

**Comment by AusBruce** [comment]
> Brian and I worked on this assignment for a while, putting in a lot of effort and time to study and conduct research. We have a few meetings to talk about the progress we have made so far. In my opinion, Brian is a highly cooperative team member who provides me with a wealth of tech expertise and insightful references.

@BrianJCal99

**Comment by maddernd** [comment]
Thanks for the work guys, 

The one thing to add to this is that the View All Units new version already exists in that other section I showed you, so there is no need to redesign this particular component. This one just needs migrating as per how the other view all units was already done. Its an interesting read though.

**Review by maddernd — APPROVED** [review]

**Comment by AusBruce** [comment]
This pull request encompasses the migration and enhancement of the f-all-units-list component. The changes aim to migrate the component, improve performance, and align with updated coding standards.
For the review:
1.The refactoring from v1 to v2 shows a clear improvement in code structure and readability. The use of Angular Material in v2 enhances the UI's consistency and modern feel.
2.The added sorting and filtering functionalities in v2 are a significant improvement. 
3.There are mentions of terminal errors in the current state of the component. Could you provide more details on these errors? It’s important to resolve these before merging the pull request.(it merged now!)
Here are some recommendations I would make:
1. Resolve the mentioned terminal errors if it is possible.
2. Add or update tests for the new functionalities.
3. Provide additional documentation or comments where necessary.
Overall，
This pull request represents a significant step forward in the application’s UI component development. The enhancements in v2 are promising, but attention to the mentioned aspects is necessary to ensure a smooth transition and integration. I recommend addressing these concerns and providing the additional information requested before proceeding with the merge.

Looking forward to the revised version and the continued improvement of our application's user  interface.
@BrianJCal99

**Pull request merged**
