### PR TITLE
Feedbackform email notification

### PR DESCRIPTION
**Pull request by CchristiNana**
# Description

This pr is about setting the email notification function for the feedback form submission. After the form is submitted, an email notification will be sent. The email address is thothtechcompanyoperation@gmail.com.
There is no new documents added.

Fixes # (issue)

## Type of change

_Please delete options that are not relevant._

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as
      expected)
- [ ] Documentation (update or new)

## How Has This Been Tested?

_Please describe the tests that you ran to verify your changes. Provide instructions so we can
reproduce. Please also list any relevant details for your test configuration_

## Testing Checklist

- [ ] Tested in latest Chrome
- [ ] Tested in latest Safari
- [ ] Tested in latest Firefox

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have requested a review from ... on the Pull Request

### CODE REVIEW

**Comment by CchristiNana** [comment]
[Create the email notification for the feedback sent by students](https://trello.com/c/hlsqMNsb/188-create-the-email-notification-for-the-feedback-sent-by-students)

**Review by Eisen666 — COMMENTED** [review]
Approve， please mentor review

**Comment by omckeon** [comment]
@CchristiNana and @Eisen666 - You need to check your PR descriptions have been properly filled out (your own and when reviewing). Please update these by Wednesday's deadline.

**Review by omckeon — APPROVED** [review]
Have tested the changes and looks to be working nicely.

**Pull request merged**
