### PR TITLE
Tutorial Vectors

### PR DESCRIPTION
**Pull request by ShaunR1991**
# Description

This tutorial will cover the fundamentals of vector mathematics and some applications (such as in game development). The intended audience will be for beginners to intermediate learners, and will guide them through understanding and implementing vector operations, including angle and magnitude calculations, vector addition and subtraction, and the dot product. It will also cover other techniques like vector normals and basic reflection, all within the context of creating dynamic game mechanics. By the end, it will lead to a greater understanding of using vectors to enhance program functionality and interactivity.

# Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as
      expected)
- [x] Documentation (update or new)

## How Has This Been Tested?

This is just a markdown file, tutorial to come.

## Testing Checklist

- [x] Tested in latest Chrome
- [x] Tested in latest Safari
- [x] Tested in latest Firefox

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have requested a review from Nidisha Pahade on the Pull Request

### CODE REVIEW

**Comment by s223126445** [comment]
All Links are working properly and there are no spelling errors. Good work on making sure of everything is accurate and well-organized in a detailed format.

**Review by s223126445 — COMMENTED** [review]
All Links are working properly and there are no spelling errors. Good work on making sure of everything is accurate and well-organized in a detailed format.

**Review by Liquidscroll — CHANGES_REQUESTED** [review]
The actual content of this PR -- the tutorial proposals -- are great work!

The issue with this is it includes commits from your previous PR ( https://github.com/thoth-tech/ThothTech-Documentation-Website/pull/85 ) and so will cause a merge conflict. This will need to be fixed.

**Comment by ShaunR1991** [comment]
The conflict with the previous PR ( https://github.com/thoth-tech/ThothTech-Documentation-Website/pull/85 ) should now be resolved. This is now the PR to work from for this proposal.

**Comment by ShaunR1991** [comment]
> The actual content of this PR -- the tutorial proposals -- are great work!
> 
> The issue with this is it includes commits from your previous PR ( #85 ) and so will cause a merge conflict. This will need to be fixed.

This has now been fixed any only contains the tutorial.

**Review by Liquidscroll — APPROVED** [review]

**Review by omckeon — APPROVED** [review]
Look forward to this tutorial :)

**Pull request merged**
