### PR TITLE
Org Chart T3 - Shiyu

### PR DESCRIPTION
**Pull request by CchristiNana**
# Description

Committed Org Chart for T3. 

Fixes # (issue)

## Type of change

_Please delete options that are not relevant._

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as
      expected)
- [ ] Documentation (update or new)

## How Has This Been Tested?

_Please describe the tests that you ran to verify your changes. Provide instructions so we can
reproduce. Please also list any relevant details for your test configuration_

## Testing Checklist

- [ ] Tested in latest Chrome
- [ ] Tested in latest Safari
- [ ] Tested in latest Firefox

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have requested a review from ... on the Pull Request

### CODE REVIEW

**Comment by CchristiNana** [comment]
[Create an Org Chart for T3](https://trello.com/c/Cjyzx6C0/89-create-an-org-chart-for-t3)

**Review by Kachi-Okorie — CHANGES_REQUESTED** [review]
You should not Overwrite an existing diagram. You create another markdown file for your new Org Chart, please revert changes

**Comment by CchristiNana** [comment]
[Migrate all Coursefow documentation to the Documentation Website](https://trello.com/c/WE4hwzLC/88-migrate-all-coursefow-documentation-to-the-documentation-website)

**Review by Kachi-Okorie — CHANGES_REQUESTED** [review]
All images should be in the public folder.

The starting of your markdown is not supported for the Documentation website. If you watched the recording for the meeting I had last week Monday you should see that every Markdown should start with a title block

**Comment by CchristiNana** [comment]
> All images should be in the public folder.
> 
> The starting of your markdown is not supported for the Documentation website. If you watched the recording for the meeting I had last week Monday you should see that every Markdown should start with a title block

**Comment by CchristiNana** [comment]
> All images should be in the public folder.
> 
> The starting of your markdown is not supported for the Documentation website. If you watched the recording for the meeting I had last week Monday you should see that every Markdown should start with a title block

**Comment by CchristiNana** [comment]
I have reverted the migrate of courseflow commit for this PR. For the Org chart t3, the image is in public folder and the markdown should be fine I think, could you approve it? Thank you so much.

**Comment by CchristiNana** [comment]
[Migrate all Coursefow documentation to the Documentation Website](https://trello.com/c/WE4hwzLC/88-migrate-all-coursefow-documentation-to-the-documentation-website)

**Comment by Kachi-Okorie** [comment]
All good, glad to see you got it working. You can send to Amin for approval

**Comment by CchristiNana** [comment]
[Review the folders in Courseflow determine which folder they fall under (Projects, Documentation, Issues and Resolution)](https://trello.com/c/KubkL8Ho/103-review-the-folders-in-courseflow-determine-which-folder-they-fall-under-projects-documentation-issues-and-resolution)

**Review by Kachi-Okorie — APPROVED** [review]

**Pull request merged**
