### PR TITLE
Create DebianDebPackaging

### PR DESCRIPTION
**Pull request by Wills2022**
Description
Documentation of work done for this enhancement:
https://trello.com/c/wXo9Dny0/432-create-debian-package-for-splashkit Have been unable to implement requested functionality, this documents the work done so far.

**This is not a change per-se, rather a log of work & research done for parent ticket**

## Type of change
- [X ] Documentation (new)

### CODE REVIEW

**Comment by omckeon** [comment]
[Debian Deb Package documentation & troubleshooting](https://trello.com/c/9hW24hfZ/470-debian-deb-package-documentation-troubleshooting)

**Comment by Eisen666** [comment]
[Populate Website with Information Provided by High Achieving Students.](https://trello.com/c/WH4WtqG4/141-populate-website-with-information-provided-by-high-achieving-students)

**Review by omckeon — COMMENTED** [review]
Can you make this PR into a Packages/Debian Package folder in this repo location: https://github.com/thoth-tech/documentation/tree/main/docs/Splashkit/Extensions ?

Also, make sure the file has the .md file extension, and check that is passes the prettier and vale tests mentioned in the CONTRIBUTING.md file in that repo.

**Comment by omckeon** [comment]
I will close this PR now as well. But can approve the next PR in the other repo.

**Pull request closed without merging**
